Check if MLTon is installed.

diff --git a/premlton b/premlton
--- a/premlton
+++ b/premlton
@@ -1,5 +1,6 @@
 #!/bin/bash
 hash preml 2>&- || { echo >&2 "PreML is not installed.  Aborting."; exit 1; }
+hash mlton 2>&- || { echo >&2 "MLTon is not installed.  Aborting."; exit 1; }
 if [ $1 ]; then
    preml "$1"
    echo "Preprocessing done.  Running mlton."
